### ISSUE TITLE
Add skip option

### ISSUE THREAD

**Issue by gsvr** [praekelt/go-jsbox-location#25]
There should be an optional 'Skip' option that can be activated for the LocationState that allows a user to not choose a location but move on from the LocationState.  So the footer would look something like:
n. Next
b. Back
s. Skip
See https://github.com/praekelt/go-jsbox-location/commit/b79bea9ea5509689a406abc54fabb5c721cc74fd for an example.

**Comment by hodgestar** [comment]
This would involve:
* Adding a `skip_text` option that defaults to `null`.
* If `skip_text` is not null, display a skip option.
* If skip is selected, call `self.next` with `null`.
