### ISSUE TITLE
Add retry option

### ISSUE THREAD

**Issue by gsvr** [praekelt/go-jsbox-location#26]
When the user reaches the last page of address options displayed, the `n. Next` option should be replaced by `r. Retry`, which should take the user back to entering their address.  This will help users that misspelled their address or didn't specify enough information and need to do another search.
See https://github.com/praekelt/go-jsbox-location/commit/fb4b031d4a02c5dd58dfc9929180eb6fd7d9d4bc for an example.

**Comment by hodgestar** [comment]
This would involve:
* Adding a `retry_text` option that defaults to `null`.
* If `retry_text` is not `null`, display a retry option.
* If `retry` is selected, call return to the internal search state.
